name: Merge to main

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      SITE_DIR: site
      PROD_TARGET_DIR: /var/sites/mshiltonj.com/initial
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ${{env.SITE_DIR}}
        run: yarn install

      - name: Build site
        working-directory: ${{env.SITE_DIR}}
        run: yarn build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_KEY }}
          log-public-key: false

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy site
        working-directory: site/dist
        run: |
          ls -altr 
          echo "Deploying site"
          rsync -avz --delete ./ webapp@${{ secrets.PROD_SSH_HOST }}:${{env.PROD_TARGET_DIR}} 

        

