name: Merge to main

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: site
        run: yarn install

      - name: Build site
        working-directory: ./app
        run: yarn build

      - name: Deploy site
        run: ls -altr site/dist

        

