name: Merge to main

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      SITE_DIR: site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ${{env.SITE_DIR}}
        run: yarn install

      - name: Build site
        working-directory: ${{env.SITE_DIR}}
        run: yarn build

      - name: Deploy site
        run: ls -altr $SITE_DIR/dist

        

